# Generated by Django 3.2.6 on 2021-08-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='created_at',
        ),
    ]
