# Generated by Django 3.2.6 on 2021-08-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_show_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='network',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
